//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package lockedCanvas

import (
	_d "encoding/xml"
	_c "fmt"
	_gd "gitee.com/greatmusicians/unioffice"
	_a "gitee.com/greatmusicians/unioffice/schema/soo/dml"
)

type LockedCanvas struct{ _a.CT_GvmlGroupShape }

func (_af *LockedCanvas) UnmarshalXML(d *_d.Decoder, start _d.StartElement) error {
	_af.CT_GvmlGroupShape = *_a.NewCT_GvmlGroupShape()
	for {
		_b, _cb := d.Token()
		if _cb != nil {
			return _c.Errorf("parsing\u0020LockedCanvas:\u0020\u0025s", _cb)
		}
		if _bb, _bf := _b.(_d.EndElement); _bf && _bb.Name == start.Name {
			break
		}
	}
	return nil
}

// Validate validates the LockedCanvas and its children
func (_ac *LockedCanvas) Validate() error { return _ac.ValidateWithPath("LockedCanvas") }
func (_ga *LockedCanvas) MarshalXML(e *_d.Encoder, start _d.StartElement) error {
	start.Attr = append(start.Attr, _d.Attr{Name: _d.Name{Local: "xmlns"}, Value: "http:\u002f\u002fschemas\u002eopenxmlformats.org\u002fdrawingml\u002f2006\u002flockedCanvas"})
//	start.Attr = append(start.Attr, _d.Attr{Name: _d.Name{Local: "xmlns:xxml"}, Value: "http:\u002f\u002fwww\u002ew3.org/XML\u002f1998/namespace"})
	start.Name.Local = "lockedCanvas"
	return _ga.CT_GvmlGroupShape.MarshalXML(e, start)
}

// ValidateWithPath validates the LockedCanvas and its children, prefixing error messages with path
func (_ae *LockedCanvas) ValidateWithPath(path string) error {
	if _gb := _ae.CT_GvmlGroupShape.ValidateWithPath(path); _gb != nil {
		return _gb
	}
	return nil
}
func NewLockedCanvas() *LockedCanvas {
	_f := &LockedCanvas{}
	_f.CT_GvmlGroupShape = *_a.NewCT_GvmlGroupShape()
	return _f
}
func init() {
	_gd.RegisterConstructor("http:\u002f\u002fschemas\u002eopenxmlformats.org\u002fdrawingml\u002f2006\u002flockedCanvas", "lockedCanvas", NewLockedCanvas)
}
